version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    container_name: instagramScrapping
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  # app:
  #   image: insta-scrapper
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     POSTGRES_USER: guidouser
  #     POSTGRES_PASSWORD: S3cret
  #     POSTGRES_DB: postgres
  #     INSTAGRAM_USERNAME: 3794143341
  #     INSTAGRAM_PASSWORD: Mama154595757
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 3000:3000
