version: '3.8'
services:
  app:
    image: scrap
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      POSTGRES_USER: guidouser
      POSTGRES_PASSWORD: S3cret
      POSTGRES_DB: postgres
      INSTAGRAM_USERNAME: 3794143341
      INSTAGRAM_PASSWORD: Mama154595757
    # depends_on:
    #   - postgres
    ports:
      - 3001:3000
